import {sha256Stable,deepFreeze} from '../../interpretation-runtime/mir7-utils.js';
export const NARRATIVE_PREVIEW_SCHEMA='PHI-OS-NARRATIVE-PREVIEW-v1.0.0';
function fail(code,details={}){const e=new Error(code);e.code=code;e.details=details;throw e;} function arr(v){return Array.isArray(v)?v:[];} function clean(v){return typeof v==='string'?v.trim():'';}
function deterministicOpening(brief){if(clean(brief.relationshipOpeningSeed))return clean(brief.relationshipOpeningSeed);const signal=arr(brief.coreThemes)[0]||arr(brief.priorityFindings)[0]||arr(brief.methodSignals)[0];return clean(signal?.statement)|| (brief.locale==='zh-Hans'?'你的完整叙事会从目前最有证据支持的核心主题开始，把不同视角放进同一条可追溯的故事线。':'Your full narrative starts from the strongest governed themes and connects them into one traceable story.');}
function questions(brief,locale){const raw=[...arr(brief.dynamicCuriosityQuestions),...arr(brief.openQuestions)];for(const s of [...arr(brief.coreThemes),...arr(brief.relationshipCoreThemes),...arr(brief.tensions)])if(clean(s?.statement))raw.push(locale==='zh-Hans'?`如果把「${clean(s.statement).slice(0,48)}」放回当前现实，最值得继续观察的是什么？`:`What becomes most useful to observe when “${clean(s.statement).slice(0,70)}” is tested against current reality?`);const out=[];for(const q of raw){const t=clean(q);if(t&&!out.includes(t))out.push(t);if(out.length===3)break;}while(out.length<3)out.push(locale==='zh-Hans'?'哪些部分目前仍然开放，而不适合过早下结论？':'Which parts remain open rather than ready for a fixed conclusion?');return out;}
export async function buildNarrativePreview({brief,offer,verifiedAiPreview=null}={}){
  if(!brief||!clean(brief.briefSemanticDigest))fail('W54N5_BRIEF_REQUIRED');if(!offer||offer.productId!=='PAID_NARRATIVE_READING_V1'||offer.purchaseMode!=='ONE_TIME')fail('W54N5_COMMERCE_OFFER_REQUIRED');if(!Number.isSafeInteger(offer.amountMinor)||!clean(offer.currency))fail('W54N5_VERSIONED_PRICE_REQUIRED');const locale=brief.relationshipIntent?.locale||brief.locale||'en';const aiValid=verifiedAiPreview?.sourceBriefDigest===brief.briefSemanticDigest&&verifiedAiPreview?.verificationPassed===true&&clean(verifiedAiPreview.openingPreview);
  const seed={schemaVersion:NARRATIVE_PREVIEW_SCHEMA,sourceBriefId:brief.briefId,sourceBriefDigest:brief.briefSemanticDigest,locale,previewMode:aiValid?'VERIFIED_AI_PREVIEW':'DETERMINISTIC_FALLBACK',openingPreview:aiValid?clean(verifiedAiPreview.openingPreview):deterministicOpening(brief),dynamicCuriosityQuestions:questions(brief,locale),fullNarrativeAdds:locale==='zh-Hans'?['把分散的结构整合成一个连贯故事','保留不同方法之间的张力与不一致','把当前现实与稳定结构分开叙述']:['Connect governed structures into one coherent story','Preserve tension and non-convergence instead of flattening them','Separate current reality from more stable structures'],offer:{productId:offer.productId,productVersion:offer.productVersion,currency:offer.currency,amountMinor:offer.amountMinor,purchaseMode:offer.purchaseMode,priceAuthorityRef:offer.priceAuthorityRef},cta:locale==='zh-Hans'?'把这些线索串成我的完整故事':'Turn these signals into my full story',productLabel:'Full Narrative Reading',priceHardcodedInRenderer:false};const previewDigest=await sha256Stable(seed);return deepFreeze({...seed,previewDigest});
}
export default Object.freeze({buildNarrativePreview});
