export const FIELD_NAMES=['observed_change','timeline','trigger','context','affected_realities','evidence','counter_evidence','dependency','current_tension','desired_transition'];
export const THRESH={observed_change:.7,timeline:.45,trigger:.4,context:.5,affected_realities:.55,evidence:.52,counter_evidence:.3,dependency:.38,current_tension:.5,desired_transition:.4};
export const PRIORITY={observed_change:1,timeline:.95,trigger:.9,evidence:.88,dependency:.86,current_tension:.84,desired_transition:.82,counter_evidence:.68,context:.64,affected_realities:.62};
export const clamp=v=>Math.min(1,Math.max(0,Number(v)||0));export const round=v=>Math.round(clamp(v)*100)/100;
export function sanitizeConversation(v){return Array.isArray(v)?v.filter(x=>['user','assistant'].includes(x?.role)&&typeof x.content==='string'&&x.content.trim()).map(x=>({role:x.role,content:x.content.trim().slice(0,4000)})).slice(-16):[]}
export function scores(v={}){return Object.fromEntries(FIELD_NAMES.map(k=>[k,round(v?.[k])]))}
export function weighted(s,w){let n=0,d=0;for(const[k,v]of Object.entries(w)){n+=clamp(s[k])*v;d+=v}return d?round(n/d):0}
export function completeness(s){const entry=weighted(s,{observed_change:.34,timeline:.2,trigger:.16,context:.12,affected_realities:.18});const recon=weighted(s,{timeline:.12,trigger:.1,context:.12,affected_realities:.1,evidence:.22,counter_evidence:.12,dependency:.22});const read=weighted(s,{evidence:.22,counter_evidence:.1,dependency:.16,current_tension:.2,desired_transition:.16,context:.08,affected_realities:.08});const entryComplete=s.observed_change>=THRESH.observed_change&&s.timeline>=THRESH.timeline&&s.trigger>=THRESH.trigger&&s.context>=THRESH.context&&s.affected_realities>=THRESH.affected_realities;const reconstructionComplete=entryComplete&&s.evidence>=THRESH.evidence&&s.counter_evidence>=THRESH.counter_evidence&&s.dependency>=THRESH.dependency;return{entryCompleteness:entry,reconstructionCompleteness:recon,readingReadiness:read,entryComplete,reconstructionComplete,readingReady:reconstructionComplete&&s.current_tension>=THRESH.current_tension&&s.desired_transition>=THRESH.desired_transition}}
export function nextTarget(s){let best='none',gap=-1;for(const k of FIELD_NAMES){if(s[k]>=THRESH[k])continue;const g=(THRESH[k]-s[k])*PRIORITY[k];if(g>gap){gap=g;best=k}}return best}
export function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8','cache-control':'no-store'}})}
export function dateContext(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuala_Lumpur',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());return{currentDate:p,currentYear:Number(p.slice(0,4)),timeZone:'Asia/Kuala_Lumpur'}}
