import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
let sharpModule;
export const ROOT=process.cwd();
export const BASE='07f525b2047498364fea5a4ae0f9a51c37a47dd1';
export const P={reg:'content/professional/method-runtime/canonical-mfig-authority-registry-v1.json',role:'content/professional/method-runtime/canonical-mfig-role-classification-registry-v1.json',runtime:'content/professional/method-runtime/mfig-visual-accuracy-runtime-v1.json',specDir:'content/professional/method-runtime/mfig-visual-spec',sourceDir:'content/professional/method-runtime/mfig-source-bindings',prod:'content/professional/method-runtime/mfig-production',style:'content/professional/method-runtime/mfig-production/mfig-style-tokens-v1.json',car:'content/professional/canonical-asset-runtime/registries/mfig-car-binding-registry-v1.json',calc:'content/professional/method-runtime/mfig-calculation-runtime-binding-registry-v1.json',proj:'content/professional/method-runtime/mfig-projection-runtime-binding-registry-v1.json'};
export const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
export const stable=x=>JSON.stringify(sortDeep(x),null,2)+'\n';
function sortDeep(x){if(Array.isArray(x))return x.map(sortDeep); if(x&&typeof x==='object'){const o={};for(const k of Object.keys(x).sort())o[k]=sortDeep(x[k]);return o;}return x;}
export const shaBytes=b=>crypto.createHash('sha256').update(b).digest('hex');
export const sha=p=>shaBytes(fs.readFileSync(p));
export const specPath=id=>`${P.specDir}/${id}.visual-spec.json`;
export const sourcePath=id=>`${P.sourceDir}/${id}.source-binding.json`;
export const manifestPath=id=>`${P.prod}/manifests/${id}.production-manifest.json`;
export const svgPath=id=>`${P.prod}/output/svg/${id}.svg`;
export const pngPath=id=>`${P.prod}/output/png/${id}.png`;
export const webpPath=id=>`${P.prod}/output/webp/${id}.webp`;
export const carPath=id=>`${P.prod}/car-candidates/${id}.car-handoff.json`;
export const ids=()=>Array.from({length:50},(_,i)=>`MFIG-${String(i+1).padStart(3,'0')}`);
export function requestedIds(argv=process.argv.slice(2)){const i=argv.indexOf('--id'); if(i>=0&&argv[i+1])return [argv[i+1]]; return ids();}
export function esc(s){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));}
export function layout(spec,style){const g=style.geometry,c=style.canvas; const n=spec.nodes.length; const cols=n<=6?Math.min(5,Math.max(1,n)):Math.min(4,Math.max(1,n)); const rows=Math.ceil(n/cols); const usableW=c.width-2*c.padding; const usableH=c.height-250; const colStep=usableW/cols; const nodeWidth=Math.max(220,Math.min(g.nodeWidth,Math.floor(colStep-24))); const rowStep=Math.min(g.nodeHeight+g.rowGap, usableH/Math.max(1,rows)); const nodes={}; spec.nodes.forEach((node,i)=>{const row=Math.floor(i/cols),rawCol=i%cols,col=(row%2===0?rawCol:cols-1-rawCol); const x=Math.round(c.padding+col*colStep+(colStep-nodeWidth)/2),y=Math.round(200+row*rowStep);nodes[node.nodeId]={x,y,width:nodeWidth,height:g.nodeHeight,row,col};}); const boundaries={}; for(const b of spec.boundaries){const boxes=b.contains.map(id=>nodes[id]).filter(Boolean); if(!boxes.length)continue; const minX=Math.min(...boxes.map(x=>x.x))-g.boundaryPadding,minY=Math.min(...boxes.map(x=>x.y))-g.boundaryPadding,maxX=Math.max(...boxes.map(x=>x.x+x.width))+g.boundaryPadding,maxY=Math.max(...boxes.map(x=>x.y+x.height))+g.boundaryPadding; boundaries[b.boundaryId]={x:minX,y:minY,width:maxX-minX,height:maxY-minY};} const edges={}; let edgeOrdinal=0; for(const e of spec.edges){edgeOrdinal++;const a=nodes[e.from],b=nodes[e.to]; if(!a||!b)continue; if(a.row===b.row){const dist=Math.abs(a.col-b.col);if(dist===1){if(b.x>a.x)edges[e.edgeId]={mode:'H',points:[[a.x+a.width,a.y+a.height/2],[b.x,b.y+b.height/2]]};else edges[e.edgeId]={mode:'H',points:[[a.x,a.y+a.height/2],[b.x+b.width,b.y+b.height/2]]};}else{const laneY=a.y+a.height+18+(edgeOrdinal%5)*10; const x1=a.x+a.width/2,x2=b.x+b.width/2;edges[e.edgeId]={mode:'ORTHO',points:[[x1,a.y+a.height],[x1,laneY],[x2,laneY],[x2,b.y+b.height]]};}}else{const x1=a.x+a.width/2,y1=a.y+a.height,x2=b.x+b.width/2,y2=b.y,midY=Math.round((y1+y2)/2);edges[e.edgeId]={mode:'ORTHO',points:[[x1,y1],[x1,midY],[x2,midY],[x2,y2]]};}} return {canvas:c,nodes,boundaries,edges};}
function wrapLabel(label,max=24){const words=String(label).split(/\s+/),lines=[];let cur='';for(const w of words){const next=cur?cur+' '+w:w;if(next.length<=max||!cur)cur=next;else{lines.push(cur);cur=w;}}if(cur)lines.push(cur);if(lines.length>2)return [lines[0],lines.slice(1).join(' ')];return lines;}
export function renderSvg(spec,style){const L=layout(spec,style),t=style.scopeTokens[spec.scope]||style.scopeTokens.SHARED,g=style.geometry,ty=style.typography; const out=[];out.push(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${style.canvas.width} ${style.canvas.height}" width="${style.canvas.width}" height="${style.canvas.height}" data-mfig-id="${esc(spec.mfigId)}" data-renderer-version="1.1.0" data-style-version="${esc(style.styleVersion)}">`);out.push(`<defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="9" refY="3" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L0,6 L9,3 z" fill="${t.stroke}"/></marker></defs>`);out.push(`<rect width="100%" height="100%" fill="${t.background}"/>`);out.push(`<text x="80" y="78" fill="${t.accent}" font-family="${ty.fontFamily}" font-size="${ty.titleSize}" font-weight="700">${esc(spec.mfigId)} · ${esc(spec.title)}</text>`);out.push(`<text x="80" y="116" fill="${t.accent}" opacity="0.75" font-family="${ty.fontFamily}" font-size="${ty.subtitleSize}">${esc(spec.scope)} · ${esc(spec.role)} · DETERMINISTIC CANONICAL SVG</text>`);
for(const b of spec.boundaries){const q=L.boundaries[b.boundaryId];if(!q)continue;out.push(`<g id="boundary-${esc(b.boundaryId)}" data-boundary-type="${esc(b.boundaryType)}"><rect x="${q.x}" y="${q.y}" width="${q.width}" height="${q.height}" rx="22" fill="none" stroke="${t.stroke}" stroke-width="2" stroke-dasharray="10 8" opacity="0.65"/><text x="${q.x+16}" y="${q.y+26}" fill="${t.accent}" font-family="${ty.fontFamily}" font-size="${ty.metaSize}">${esc(b.boundaryId)}</text></g>`)}
for(const e of spec.edges){const q=L.edges[e.edgeId];if(!q)continue;const d=q.points.map((p,i)=>`${i?'L':'M'} ${p[0]} ${p[1]}`).join(' ');out.push(`<g id="edge-${esc(e.edgeId)}" data-from="${esc(e.from)}" data-to="${esc(e.to)}" data-relation="${esc(e.relation)}"><path d="${d}" fill="none" stroke="${t.stroke}" stroke-width="${g.edgeWidth}" stroke-linejoin="round" marker-end="url(#arrow)"/></g>`)}
for(const n of spec.nodes){const q=L.nodes[n.nodeId],lines=wrapLabel(n.displayLabel);const y0=q.y+(lines.length===1?48:38);let text=`<text x="${q.x+q.width/2}" y="${y0}" text-anchor="middle" fill="${t.accent}" font-family="${ty.fontFamily}" font-size="${ty.nodeSize}" font-weight="700">`;lines.forEach((line,i)=>{text+=`<tspan x="${q.x+q.width/2}" dy="${i===0?0:24}">${esc(line)}</tspan>`});text+='</text>';out.push(`<g id="node-${esc(n.nodeId)}" data-mfig-node="${esc(n.nodeId)}" data-authority-class="${esc(n.authorityClass)}" data-semantic-role="${esc(n.semanticRole)}"><rect x="${q.x}" y="${q.y}" width="${q.width}" height="${q.height}" rx="${g.nodeRadius}" fill="${t.panel}" stroke="${t.stroke}" stroke-width="2"/>${text}<text x="${q.x+q.width/2}" y="${q.y+q.height-18}" text-anchor="middle" fill="${t.accent}" opacity="0.65" font-family="${ty.fontFamily}" font-size="12">${esc(n.authorityClass)}</text></g>`)}
let sy=style.canvas.height-86; const states=spec.mustState.slice(0,3).join('  ·  ');out.push(`<text x="80" y="${sy}" fill="${t.accent}" opacity="0.8" font-family="${ty.fontFamily}" font-size="14">${esc(states)}</text>`);out.push('</svg>'); return out.join('\n')+'\n';}
export const geometryFingerprint=(spec,style)=>shaBytes(Buffer.from(stable(layout(spec,style))));
export function ensureDir(p){fs.mkdirSync(p,{recursive:true});}
export function writeFile(p,data){ensureDir(path.dirname(p));fs.writeFileSync(p,data);}
export async function rasterize(svg,png,webp){ensureDir(path.dirname(png));ensureDir(path.dirname(webp)); try{sharpModule??=require('sharp');}catch(error){throw new Error(`Repository raster backend unavailable. Run npm ci so the pinned sharp dependency is installed. ${error?.message||error}`);} const input=fs.readFileSync(svg),opts={density:96,unlimited:false,failOn:'error'},image=sharpModule(input,opts); await Promise.all([image.clone().png({compressionLevel:6,adaptiveFiltering:false,palette:false,effort:4}).toFile(png),image.clone().webp({quality:92,alphaQuality:100,effort:4,smartSubsample:false,lossless:false}).toFile(webp)]);}
export function entryById(id){const e=read(P.reg).entries.find(x=>x.mfigId===id); if(!e)throw new Error(`Unknown ${id}`); return e;}
