/** MIR-3 26-activation builder from governed upstream astronomy records. */
import {resolveGateLine} from './gate-line.js';
export const ACTIVATION_BODIES=Object.freeze(['SUN','EARTH','MOON','NORTH_NODE','SOUTH_NODE','MERCURY','VENUS','MARS','JUPITER','SATURN','URANUS','NEPTUNE','PLUTO']);
function normalizeLongitude(x){if(!Number.isFinite(x))throw new TypeError('ASTRONOMY_LONGITUDE_REQUIRED');return ((x%360)+360)%360;}
function circularDistance(a,b){const d=Math.abs(normalizeLongitude(a)-normalizeLongitude(b));return Math.min(d,360-d);}
function validateOpposites(astro,layer){if(Number.isFinite(astro.longitudes?.SUN)&&Number.isFinite(astro.longitudes?.EARTH)&&circularDistance(astro.longitudes.EARTH,normalizeLongitude(astro.longitudes.SUN+180))>1e-8)throw new TypeError(`EARTH_OPPOSITION_MISMATCH:${layer}`);if(Number.isFinite(astro.longitudes?.NORTH_NODE)&&Number.isFinite(astro.longitudes?.SOUTH_NODE)&&circularDistance(astro.longitudes.SOUTH_NODE,normalizeLongitude(astro.longitudes.NORTH_NODE+180))>1e-8)throw new TypeError(`SOUTH_NODE_OPPOSITION_MISMATCH:${layer}`);}
export function buildActivationRecords({personalityAstronomy,designAstronomy,designMomentRef=null,nodeConvention}){
  const records=[];for(const [layer,astro] of [['PERSONALITY',personalityAstronomy],['DESIGN',designAstronomy]]){if(!astro||typeof astro!=='object')throw new TypeError(`${layer}_ASTRONOMY_REQUIRED`);for(const bodyCode of ACTIVATION_BODIES){const id=`${layer}-${bodyCode}`;const isNode=bodyCode==='NORTH_NODE'||bodyCode==='SOUTH_NODE';if(isNode&&(!nodeConvention||nodeConvention==='PHI_OS_AST_NODE_NONE_V1')){records.push(Object.freeze({activationId:id,layer,bodyCode,status:'UNKNOWN',unknownReason:'CANONICAL_NODE_MODE_NOT_AVAILABLE',instantUTC:astro.instantUTC||astro.utcIso||null,eclipticLongitude:null,gateWheelAngle:null,gate:null,line:null,positionWithinGateDeg:null,positionWithinLineDeg:null,mappingVersion:'PHI-OS-GATE-WHEEL-v1.0.0',astronomyRef:astro.astronomyRef||astro.sourceRef||null,designMomentRef:layer==='DESIGN'?designMomentRef:null,lineage:Object.freeze({nodeConvention:nodeConvention||'UNRESOLVED'})}));continue;}let lon=astro.longitudes?.[bodyCode];if(bodyCode==='EARTH'&&lon==null&&Number.isFinite(astro.longitudes?.SUN))lon=normalizeLongitude(astro.longitudes.SUN+180);if(bodyCode==='SOUTH_NODE'&&lon==null&&Number.isFinite(astro.longitudes?.NORTH_NODE))lon=normalizeLongitude(astro.longitudes.NORTH_NODE+180);if(!Number.isFinite(lon))throw new TypeError(`ASTRONOMY_BODY_MISSING:${layer}:${bodyCode}`);const r=resolveGateLine(lon);records.push(Object.freeze({activationId:id,layer,bodyCode,status:'CALCULATED',instantUTC:astro.instantUTC||astro.utcIso||null,eclipticLongitude:r.eclipticLongitude,gateWheelAngle:r.gateWheelAngle,gate:r.gate,line:r.line,positionWithinGateDeg:r.positionWithinGateDeg,positionWithinLineDeg:r.positionWithinLineDeg,positionWithinLineRatio:r.positionWithinLineRatio,boundaryExact:r.boundaryExact,mappingVersion:'PHI-OS-GATE-WHEEL-v1.0.0',astronomyRef:astro.astronomyRef||astro.sourceRef||null,designMomentRef:layer==='DESIGN'?designMomentRef:null,lineage:Object.freeze({nodeConvention:nodeConvention||null})}));}}
  return Object.freeze(records);
}
