import {deepFreeze,sha256Stable} from '../../interpretation-runtime/mir7-utils.js';
const STATES=Object.freeze(['PENDING','ACTIVE','GRACE','PAST_DUE','CANCEL_AT_PERIOD_END','CANCELED','SUSPENDED']);
function fail(code,details={}){const e=new Error(code);e.code=code;e.details=details;throw e;}
function text(v,code){const s=String(v??'').trim();if(!s)fail(code);return s;}
function arr(v){return Array.isArray(v)?v:[];}
function allowedTransition(from,to){const map={PENDING:['ACTIVE','CANCELED'],ACTIVE:['GRACE','PAST_DUE','CANCEL_AT_PERIOD_END','CANCELED','SUSPENDED'],GRACE:['ACTIVE','PAST_DUE','CANCELED','SUSPENDED'],PAST_DUE:['ACTIVE','GRACE','CANCELED','SUSPENDED'],CANCEL_AT_PERIOD_END:['ACTIVE','CANCELED'],CANCELED:['ACTIVE'],SUSPENDED:['ACTIVE','CANCELED']};return map[from]?.includes(to)===true;}
export function transitionContinuityEntitlement(entitlement,nextState){if(!STATES.includes(entitlement?.state)||!STATES.includes(nextState))fail('CONTINUITY_STATE_INVALID');if(!allowedTransition(entitlement.state,nextState))fail('CONTINUITY_STATE_TRANSITION_FORBIDDEN',{from:entitlement.state,to:nextState});return deepFreeze({...entitlement,state:nextState});}
export function createContinuityEntitlement({subscriptionId,subjectRef,planId,state='PENDING',periodStart=null,periodEnd=null,quotas={}}={}){if(!STATES.includes(state))fail('CONTINUITY_STATE_INVALID');return deepFreeze({schemaVersion:'PHI-OS-CONTINUITY-ENTITLEMENT-v1.0.0',subscriptionId:text(subscriptionId,'CONTINUITY_SUBSCRIPTION_ID_REQUIRED'),subjectRef:text(subjectRef,'CONTINUITY_SUBJECT_REQUIRED'),planId:text(planId,'CONTINUITY_PLAN_REQUIRED'),state,periodStart,periodEnd,quotas:{continuityNarrativesRemaining:Number.isSafeInteger(quotas.continuityNarrativesRemaining)?quotas.continuityNarrativesRemaining:null,askThisReadingRemaining:Number.isSafeInteger(quotas.askThisReadingRemaining)?quotas.askThisReadingRemaining:null,askThisRelationshipRemaining:Number.isSafeInteger(quotas.askThisRelationshipRemaining)?quotas.askThisRelationshipRemaining:null},quotaAuthority:'SERVER_ENTITLEMENT'});}
export async function buildContinuityContextIR({subjectRef,originalReadingRef,originalNarrativeRef,currentReality=[],realityHistory=[],timingContext=[],observationTargets=[],priorContinuityNarratives=[],openQuestions=[],profileSnapshots=[],assessmentRetakes=[],relationship=null,selectedSourceIds=[]}={}){
 const subject=text(subjectRef,'CONTINUITY_SUBJECT_REQUIRED');const selected=new Set(arr(selectedSourceIds).map(String));
 const catalog=[...arr(currentReality),...arr(realityHistory),...arr(timingContext),...arr(observationTargets),...arr(priorContinuityNarratives),...arr(openQuestions),...arr(profileSnapshots),...arr(assessmentRetakes)].map((value,index)=>({id:String(value?.id??value?.ref??`SRC-${index+1}`),kind:String(value?.kind??'SELECTED_CONTEXT'),value}));
 if(relationship)catalog.push({id:String(relationship.id??relationship.ref??'RELATIONSHIP-CONTEXT'),kind:'RELATIONSHIP_CONTEXT',value:relationship});
 const picked=catalog.filter(x=>selected.has(x.id));
 if(picked.length!==selected.size)fail('CONTINUITY_SELECTED_SOURCE_NOT_FOUND');
 const semanticDigest=await sha256Stable({subject,originalReadingRef,originalNarrativeRef,picked});
 return deepFreeze({schemaVersion:'PHI-OS-CONTINUITY-CONTEXT-IR-v1.0.0',contextId:`CONTCTX-${semanticDigest.slice(0,24).toUpperCase()}`,subjectRef:subject,originalReadingRef:originalReadingRef??null,originalNarrativeRef:originalNarrativeRef??null,selectedSources:picked,semanticDigest,governance:{silentHistoricalImport:false,explicitSelectionRequired:true,profileImportedOnlyWhenSelected:true,relationshipImportedOnlyWhenSelected:true}});
}
export async function buildContinuityNarrativeDelta({context,changed=[],stable=[],moreRelevant=[],lessRelevant=[],contradictions=[],newlyOpen=[],observeNext=[],profileDelta=null,relationshipDelta=null}={}){
 if(context?.schemaVersion!=='PHI-OS-CONTINUITY-CONTEXT-IR-v1.0.0')fail('CONTINUITY_CONTEXT_REQUIRED');
 const body={changed:arr(changed),stable:arr(stable),moreRelevant:arr(moreRelevant),lessRelevant:arr(lessRelevant),contradictions:arr(contradictions),newlyOpen:arr(newlyOpen),observeNext:arr(observeNext)};
 if(profileDelta!==null&&profileDelta?.newProfileInput!==true)fail('CONTINUITY_PROFILE_DELTA_REQUIRES_NEW_INPUT');
 if(relationshipDelta!==null&&relationshipDelta?.fullRelationshipNarrativeRegenerated===true)fail('CONTINUITY_RELATIONSHIP_DELTA_ONLY');
 const semanticDigest=await sha256Stable({contextId:context.contextId,...body,profileDelta,relationshipDelta});
 return deepFreeze({schemaVersion:'PHI-OS-CONTINUITY-NARRATIVE-DELTA-v1.0.0',deltaId:`CONTDELTA-${semanticDigest.slice(0,24).toUpperCase()}`,contextId:context.contextId,...body,profileDelta,relationshipDelta,semanticDigest,governance:{fullOriginalIdentityNarrativeRepeated:false,timingIsContextNotPrediction:true,currentRealityMayContradict:true}});
}
export function consumeContinuityQuota(entitlement,quota,amount=1){if(!['ACTIVE','GRACE','CANCEL_AT_PERIOD_END'].includes(entitlement?.state))fail('CONTINUITY_ENTITLEMENT_NOT_ACTIVE');const key={ASK_THIS_READING:'askThisReadingRemaining',ASK_THIS_RELATIONSHIP:'askThisRelationshipRemaining',CONTINUITY_NARRATIVE:'continuityNarrativesRemaining'}[quota];if(!key)fail('CONTINUITY_QUOTA_KIND_INVALID');const current=entitlement.quotas?.[key];if(!Number.isSafeInteger(current))fail('CONTINUITY_QUOTA_NOT_CONFIGURED');if(current<amount)fail('CONTINUITY_QUOTA_EXHAUSTED');return deepFreeze({...entitlement,quotas:{...entitlement.quotas,[key]:current-amount}});}
export function assertAskThisProfileRoutedExternally(kind){if(kind==='ASK_THIS_PROFILE')fail('CONTINUITY_ASK_THIS_PROFILE_MUST_ROUTE_CX_R9_R2');return true;}
export const CONTINUITY_ENTITLEMENT_STATES=STATES;
