"""Build a changes-only archive against the user-specified current main."""
import hashlib
import json
import subprocess
from pathlib import Path
from zipfile import ZipFile, ZipInfo, ZIP_DEFLATED

ROOT = Path(__file__).resolve().parent.parent
BASELINE = 'e192653ff4fbafad1feaffb9dc1c0fa4073ad215'
DEST = ROOT / 'output/delta'
NAME = 'VRPT-R1-COMMERCE-CROSS-HP-e192653'


def git(*args):
    return subprocess.check_output(['git', *args], cwd=ROOT)


if git('rev-parse', 'HEAD').decode().strip() != BASELINE:
    raise SystemExit('Baseline changed: inspect the new user changes before rebuilding.')
tracked = git('diff', '--name-only', '--no-renames', '-z', BASELINE).decode().split('\0')
untracked = git('ls-files', '--others', '--exclude-standard', '-z').decode().split('\0')
paths = sorted(set(p for p in tracked + untracked if p and not p.startswith(('output/delta/', '.git/', '.tmp/', 'node_modules/'))))
records, deleted, contents = [], [], {}
for name in paths:
    target = (ROOT / name).resolve()
    if ROOT not in target.parents:
        raise SystemExit('Archive path outside workspace')
    if not target.exists():
        deleted.append(name)
        continue
    data = target.read_bytes()
    old = subprocess.run(['git', 'show', f'{BASELINE}:{name}'], cwd=ROOT, capture_output=True)
    record = dict(path=name, action='MODIFIED' if old.returncode == 0 else 'ADDED',
                  sha256=hashlib.sha256(data).hexdigest(), bytes=len(data))
    if old.returncode == 0:
        record['baselineSha256'] = hashlib.sha256(old.stdout).hexdigest()
    records.append(record)
    contents[name] = data

manifest = dict(work='VRPT-R1 + PWS Commerce successor + Cross HD/Profile review',
                baseline=BASELINE, originalImplementationBaseline='013d3aa6e9d09ab079d0696a5d0b15905fac0783',
                customerProductionActivated=False, files=records, deleted=deleted,
                payloadFileCount=len(records), archiveEntryCount=len(records) + 2)
replay = f'''# Changes-only replay

Baseline: {BASELINE}. This main already contains the preceding VRPT/Commerce/Cross candidate implementation.
This archive contains only this continuation's added or modified files, not a repository snapshot.

1. Use a separate clean checkout at the exact baseline. Confirm `git rev-parse HEAD` and empty `git status --porcelain`.
2. Before extraction, verify each MODIFIED file's baselineSha256 against MANIFEST.json. Reject a nonempty destination for every ADDED path. Do not overwrite uncommitted user work.
3. Extract payload paths into that checkout. MANIFEST.json and REPLAY.md are delivery metadata, not repository source files. Review the deleted list separately; this archive performs no deletions.
4. Verify every payload SHA-256 and byte count against MANIFEST.json.
5. With the repository dependencies installed, run:

   node scripts/check-pws-report-successor.mjs
   node scripts/check-cross-hd-profile-successor.mjs
   node scripts/build-cross-successor-handoff.mjs
   node scripts/build-visual-report-review.mjs
   npm run check:vrpt-r1
   npm run check

   On Windows use scripts/run-check-windows.ps1 for the same npm lifecycle with nested PATH normalization.
   PHIOS_GIT_BIN may point to the installed Git executable; no global npm configuration change is needed.

6. Start `node scripts/preview-ecr-full-review.mjs`; set PHIOS_REVIEW_URL to its printed local origin.
   Set PHIOS_PLAYWRIGHT_MODULE to a local Playwright index.mjs; install/use Edge for its msedge channel.
   Run `node scripts/check-visual-report-browser.mjs --pdf` and `node scripts/check-visual-report-review-surfaces.mjs`.
   Run `python scripts/check-visual-report-pdfs.py --poppler-bin <poppler-bin>` with pypdf and Pillow installed.
7. Open docs/visual-report-r1/final-review.html through that local server. Review reports, Commerce selection, Cross HD/Profile mappings and PIS-R1 together. Human acceptance is not generated by these scripts.

No commit, push, deployment, Stripe activation or new Cross production admission is part of replay.
'''
contents['MANIFEST.json'] = (json.dumps(manifest, ensure_ascii=False, indent=2) + '\n').encode()
contents['REPLAY.md'] = replay.encode()
DEST.mkdir(parents=True, exist_ok=True)
(DEST / f'{NAME}.manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
archive = DEST / f'{NAME}.zip'
with ZipFile(archive, 'w', compression=ZIP_DEFLATED, compresslevel=6) as z:
    for name, data in sorted(contents.items()):
        info = ZipInfo(name, date_time=(2026, 9, 17, 0, 0, 0))
        info.compress_type = ZIP_DEFLATED
        z.writestr(info, data)
with ZipFile(archive) as z:
    assert z.testzip() is None
    assert len(z.namelist()) == len(records) + 2
    for record in records:
        assert hashlib.sha256(z.read(record['path'])).hexdigest() == record['sha256']
delivery = dict(archive=archive.relative_to(ROOT).as_posix(), baseline=BASELINE,
                sha256=hashlib.sha256(archive.read_bytes()).hexdigest(), bytes=archive.stat().st_size,
                payloadFileCount=len(records), archiveEntryCount=len(contents), deletedCount=len(deleted),
                verification='ZIP CRC and every payload SHA-256 verified', productionAdmission=False)
(DEST / f'{NAME}.delivery.json').write_text(json.dumps(delivery, indent=2) + '\n', encoding='utf-8')
print(json.dumps(delivery))
