import {normalizeTwoPersonRelationalContext} from './two-person-context-runtime.js';
import {routeRelationalQuestion} from './relational-route-runtime.js';
import {buildAstRelationalStructuralProjection} from './ast-relational-runtime.js';
import {buildHdrInternalRelationalProjection} from './hdr-internal-relational-runtime.js';
import {buildZiWeiRelationshipDomainContext} from './zi-wei-relationship-context-runtime.js';
import {buildBzrRelationalTemporalContext} from './bzr-relational-context-runtime.js';
import {buildRelationalReadingIR} from './relational-reading-ir.js';
export const RLR_RUNTIME_CODE='PHI_OS_RELATIONAL_RUNTIME';
export const RLR_RUNTIME_VERSION='1.0.0';
export async function executeRelationalRuntime({question,pairContext:rawPairContext,personA,personB,realityEvidence=[]}={}){const pairContext=normalizeTwoPersonRelationalContext(rawPairContext);const routePlan=routeRelationalQuestion({question,publicRequest:pairContext.publicRequest,internalAccessClass:pairContext.internalAccessClass});const astRelationalProjection=await buildAstRelationalStructuralProjection({pairContext,personAReading:personA?.astNatalReading,personBReading:personB?.astNatalReading});const ziWeiRelationshipDomainContext=personA?.ziWeiNatalReading&&personB?.ziWeiNatalReading?buildZiWeiRelationshipDomainContext({pairContext,personAReading:personA.ziWeiNatalReading,personBReading:personB.ziWeiNatalReading}):null;const bzrRelationalTemporalContext=personA?.bzrTemporalReading&&personB?.bzrTemporalReading?buildBzrRelationalTemporalContext({pairContext,personAReading:personA.bzrTemporalReading,personBReading:personB.bzrTemporalReading,relationshipTargetDate:personA.bzrTemporalReading.sections?.currentAnnualContext?.targetContext?.targetDate}):null;let hdrInternalRelationalProjection=null;if(personA?.hdrOperatingReading||personB?.hdrOperatingReading){if(!personA?.hdrOperatingReading||!personB?.hdrOperatingReading)throw Object.assign(new Error('RLR_HDR_RELATIONAL_REQUIRES_BOTH_PERSONS'),{code:'RLR_HDR_RELATIONAL_REQUIRES_BOTH_PERSONS',status:400});hdrInternalRelationalProjection=await buildHdrInternalRelationalProjection({pairContext,personAReading:personA.hdrOperatingReading,personBReading:personB.hdrOperatingReading});}const reading=await buildRelationalReadingIR({pairContext,routePlan,astRelationalProjection,hdrInternalRelationalProjection,ziWeiRelationshipDomainContext,bzrRelationalTemporalContext,realityEvidence});return Object.freeze({schemaVersion:'PHI-OS-RELATIONAL-RUNTIME-RESULT-v1.0.0',runtimeCode:RLR_RUNTIME_CODE,runtimeVersion:RLR_RUNTIME_VERSION,routePlan,pairContext,components:Object.freeze({astRelationalProjection,hdrInternalRelationalProjection,ziWeiRelationshipDomainContext,bzrRelationalTemporalContext}),reading,publicExecutionAllowed:pairContext.publicRequest,internalHdrComponentIncluded:Boolean(hdrInternalRelationalProjection),boundaries:Object.freeze({natalMethodsRecalculated:false,compatibilityScoreCreated:false,relationshipVerdictCreated:false,methodVotingCreated:false,realityEvidenceFinalAuthority:true})});}
