import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { digest, serialize } from './canonical-brief-v2.mjs';
import { validateZhHansCandidate } from './zh-hans-candidate-v1.mjs';
import { validateHumanReview } from './human-review-v1.mjs';
import { validateHumanApproval } from './human-approval-v1.mjs';
export const PUBLICATION_SCHEMA_VERSION='PHI-OS-PUBLICATION-PACKAGE-v1.0.0';
export const PUBLICATION_TYPE='canonical_article_publication';
const fail=(code,message)=>Object.assign(new Error(`${code}: ${message}`),{code});
const exists=file=>fs.access(file).then(()=>true,()=>false);
export function publicationWithoutDigest(value){const copy=structuredClone(value);delete copy.publicationDigest;return copy;}
export function computePublicationDigest(value){return digest(publicationWithoutDigest(value));}
export async function buildPublication(root,{candidate,review,approval,publisherCode='TL',publishedAt,version='1.0.0'}){
 const cv=await validateZhHansCandidate(root,candidate,{briefPath:null});if(!cv.valid)throw fail('PUBLICATION_REQUIRES_VALID_CANDIDATE',JSON.stringify(cv.errors));
 const rv=validateHumanReview(review,candidate);if(!rv.valid||review.decision!=='accept')throw fail('PUBLICATION_REQUIRES_ACCEPTED_REVIEW',JSON.stringify(rv.errors));
 const av=validateHumanApproval(approval,candidate,review);if(!av.valid||approval.decision!=='approve')throw fail('PUBLICATION_REQUIRES_APPROVAL',JSON.stringify(av.errors));
 if(!publishedAt||Number.isNaN(Date.parse(publishedAt)))throw fail('PUBLISHED_AT_INVALID',String(publishedAt));
 const slug=candidate.sourceBrief?.briefCode?candidate.nodeCode.toLowerCase():candidate.nodeCode.toLowerCase();
 const briefPath=`content/knowledge/production/briefs/zh-Hans/${candidate.nodeCode}-production-brief.v2.json`;
 const brief=JSON.parse(await fs.readFile(path.join(root,briefPath),'utf8'));
 const articleCode=`KA-${candidate.nodeCode.replace(/^KN-/,'')}-ZH-ARTICLE`;
 const payload={publicationType:PUBLICATION_TYPE,publicationSchemaVersion:PUBLICATION_SCHEMA_VERSION,publicationCode:`PUBLICATION-${approval.approvalCode}-V1`,candidate:{candidateCode:candidate.candidateCode,candidateDigest:candidate.candidateDigest,nodeCode:candidate.nodeCode,locale:candidate.locale},review:{reviewCode:review.reviewCode,reviewDigest:review.reviewDigest,decision:review.decision},approval:{approvalCode:approval.approvalCode,approvalDigest:approval.approvalDigest,decision:approval.decision},publisher:{publisherCode,authority:'TL Independent Publication Authority'},decision:'publish',article:{articleCode,nodeCode:candidate.nodeCode,locale:candidate.locale,title:candidate.article.title,summary:candidate.article.summary,bodyMarkdown:candidate.article.bodyMarkdown,slug:brief.localizedIdentity.slug,href:`/articles/${brief.localizedIdentity.slug}`,version},authority:{canonicalMeaning:'TL',review:'human_review_accepted',approval:'human_approval_recorded',publication:'independent_publication_recorded'},governance:{candidateMutationAllowed:false,reviewMutationAllowed:false,approvalMutationAllowed:false,knowledgeRegistryMutationAllowed:false,publicRuntimeProjectionWritten:false,localeInheritanceAllowed:false},publishedAt:new Date(publishedAt).toISOString()};
 return {...payload,publicationDigest:computePublicationDigest(payload)};
}
export function validatePublication(value,candidate,review,approval){const errors=[],add=(code,message)=>errors.push({code,message});if(!value||typeof value!=='object')return {valid:false,errors:[{code:'PUBLICATION_NOT_OBJECT',message:'Publication must be object.'}]};
 if(value.publicationType!==PUBLICATION_TYPE)add('PUBLICATION_TYPE_INVALID',String(value.publicationType));if(value.publicationSchemaVersion!==PUBLICATION_SCHEMA_VERSION)add('PUBLICATION_SCHEMA_VERSION_INVALID',String(value.publicationSchemaVersion));if(value.decision!=='publish')add('PUBLICATION_DECISION_INVALID',String(value.decision));
 if(value.review?.decision!=='accept'||value.approval?.decision!=='approve')add('PUBLICATION_INPUT_STATE_INVALID','review/approval');if(value.authority?.publication!=='independent_publication_recorded')add('PUBLICATION_AUTHORITY_INVALID',JSON.stringify(value.authority));
 for(const k of ['candidateMutationAllowed','reviewMutationAllowed','approvalMutationAllowed','knowledgeRegistryMutationAllowed','publicRuntimeProjectionWritten','localeInheritanceAllowed'])if(value.governance?.[k]!==false)add('PUBLICATION_GOVERNANCE_INVALID',k);
 if(!value.publishedAt||Number.isNaN(Date.parse(value.publishedAt)))add('PUBLISHED_AT_INVALID',String(value.publishedAt));if(!/^[a-f0-9]{64}$/.test(value.publicationDigest||''))add('PUBLICATION_DIGEST_FORMAT_INVALID','publicationDigest');else if(value.publicationDigest!==computePublicationDigest(value))add('PUBLICATION_DIGEST_INVALID','publicationDigest');
 if(candidate)for(const k of ['candidateCode','candidateDigest','nodeCode','locale'])if(value.candidate?.[k]!==candidate[k])add('PUBLICATION_CANDIDATE_BINDING_INVALID',k);if(review)for(const k of ['reviewCode','reviewDigest','decision'])if(value.review?.[k]!==review[k])add('PUBLICATION_REVIEW_BINDING_INVALID',k);if(approval)for(const k of ['approvalCode','approvalDigest','decision'])if(value.approval?.[k]!==approval[k])add('PUBLICATION_APPROVAL_BINDING_INVALID',k);
 return {valid:errors.length===0,errors,publicationCode:value.publicationCode,publicationDigest:value.publicationDigest};}
export function buildPublicationRegistryRecord(p){return {publicationCode:p.publicationCode,publicationDigest:p.publicationDigest,articleCode:p.article.articleCode,nodeCode:p.article.nodeCode,locale:p.article.locale,candidateCode:p.candidate.candidateCode,candidateDigest:p.candidate.candidateDigest,reviewCode:p.review.reviewCode,reviewDigest:p.review.reviewDigest,approvalCode:p.approval.approvalCode,approvalDigest:p.approval.approvalDigest,publisherCode:p.publisher.publisherCode,decision:p.decision,publishedAt:p.publishedAt,publicRuntimeProjection:'not_projected'};}
export async function writePublicationPackage(root,p,{apply=false,output}={}){const rel=output||`content/knowledge/production/publications/${p.article.locale}/${p.article.nodeCode}/publication.v1.json`,target=path.join(root,rel);if(await exists(target))throw fail('PUBLICATION_TARGET_EXISTS',rel);if(apply){await fs.mkdir(path.dirname(target),{recursive:true});const tmp=`${target}.tmp-${process.pid}-${crypto.randomUUID()}`;await fs.writeFile(tmp,serialize(p),{flag:'wx'});await fs.rename(tmp,target);}return {applied:apply,mode:apply?'apply':'dry-run',targetPath:rel};}
export async function registerPublicationProjection(root,record,{apply=false}={}){const rel='content/knowledge/production/registry/publication-registry.json',file=path.join(root,rel),registry=JSON.parse(await fs.readFile(file,'utf8'));if(registry.records.some(x=>x.publicationCode===record.publicationCode))throw fail('PUBLICATION_REGISTRY_RECORD_EXISTS',record.publicationCode);const next={...registry,records:[...registry.records,record].sort((a,b)=>a.publicationCode.localeCompare(b.publicationCode))};if(apply){const tmp=`${file}.tmp-${process.pid}-${crypto.randomUUID()}`;await fs.writeFile(tmp,serialize(next),{flag:'wx'});await fs.rename(tmp,file);}return {applied:apply,mode:apply?'apply':'dry-run',registryPath:rel};}
