import {sha256} from '../method-runtime/shared-calculation-runtime.js';
import {createAstronomyEngineProductionAdapters} from '../method-client-delivery/production-adapters/astronomy-engine-production-adapter.js';
import {ASTA_ASPECT_POLICY,ASTA_CORE_BODY_CODES} from '../ast-production/ast-production-policy.js';

export const AST_TRANSIT_PROJECTION_SCHEMA='PHI-OS-AST-TRANSIT-PROJECTION-v1.0.0';
export const AST_TRANSIT_RUNTIME_VERSION='2.0.0';
const ANGLE_CODES=Object.freeze(['ASC','MC','DSC','IC']);
const SIGNS=Object.freeze(['ARIES','TAURUS','GEMINI','CANCER','LEO','VIRGO','LIBRA','SCORPIO','SAGITTARIUS','CAPRICORN','AQUARIUS','PISCES']);
function fail(code,status=422){const e=new Error(code);e.code=code;e.status=status;throw e;}
function freeze(v){if(v&&typeof v==='object'&&!Object.isFrozen(v)){Object.freeze(v);for(const x of Object.values(v))freeze(x)}return v;}
function norm(v){if(!Number.isFinite(v))fail('ASTT_LONGITUDE_INVALID',400);return Number((((v%360)+360)%360).toFixed(12));}
function separation(a,b){let d=Math.abs(norm(a)-norm(b));if(d>180)d=360-d;return Number(d.toFixed(12));}
function aspectMatch(sep){const c=ASTA_ASPECT_POLICY.map(p=>({...p,orb:Number(Math.abs(sep-p.angleDegrees).toFixed(12))})).filter(x=>x.orb<=x.orbDegrees).sort((a,b)=>a.orb-b.orb||a.priority-b.priority);return c[0]||null;}
function parseOffset(value){if(!/^[+-](?:0\d|1[0-4]):[0-5]\d$/.test(value||''))fail('ASTT_TARGET_UTC_OFFSET_INVALID',400);const sign=value[0]==='-'?-1:1;return sign*(Number(value.slice(1,3))*60+Number(value.slice(4,6)));}
function validDate(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))return false;const d=new Date(`${value}T00:00:00Z`);return !Number.isNaN(d.valueOf())&&d.toISOString().slice(0,10)===value;}
function validTime(value){return /^(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d$/.test(value||'');}
function normalizeTargetContext(targetContext){const date=targetContext?.targetDate,time=targetContext?.targetTime,tz=targetContext?.targetTimezone||{};if(!validDate(date))fail('ASTT_TARGET_DATE_REQUIRED',400);if(!validTime(time))fail('ASTT_TARGET_TIME_REQUIRED',400);if(typeof tz.iana!=='string'||!tz.iana.trim())fail('ASTT_TARGET_TIMEZONE_REQUIRED',400);const offsetMinutes=parseOffset(tz.utcOffsetAtTarget);const d=new Date(`${date}T${time}${tz.utcOffsetAtTarget}`);if(Number.isNaN(d.valueOf()))fail('ASTT_TARGET_LOCAL_TIME_INVALID',400);return freeze({targetDate:date,targetTime:time,targetTimezone:{iana:tz.iana.trim(),utcOffsetAtTarget:tz.utcOffsetAtTarget,offsetMinutes,source:'EXPLICIT_REQUEST'},targetUtcIso:d.toISOString()});}
function assertNatal(p){const mpa=p?.execution?.mpaDecision;const dispatchEvidence=(p?.evidence||[]).some(x=>x?.type==='PRODUCTION_DISPATCH_AUTHORITY'&&x?.status==='AVAILABLE');if(p?.schemaVersion!=='PHI-OS-CANONICAL-METHOD-PROJECTION-v2.0.0'||p?.method?.publicMethodCode!=='ASTROLOGY_PROJECTION'||p?.projection?.productionResult!==true||p?.projection?.clientRenderable!==true||p?.interpretation?.included!==false||mpa?.authorityOwner!=='MPA'||mpa?.decision!=='ELIGIBLE'||mpa?.dispatchAllowed!==true||!dispatchEvidence)fail('ASTT_ACCEPTED_NATAL_PROJECTION_REQUIRED',400);}
function natalPoints(p){const pos=new Map((p.calculation?.positions||[]).filter(x=>ASTA_CORE_BODY_CODES.includes(x.code)).map(x=>[x.code,{targetType:'PLANET',code:x.code,longitude:norm(Number(x.value))}]));if(pos.size!==ASTA_CORE_BODY_CODES.length)fail('ASTT_NATAL_CORE10_REQUIRED',400);const angles=(p.calculation?.structures||[]).find(x=>x.code==='ANGLES')?.items||[];for(const x of angles)if(ANGLE_CODES.includes(x.code))pos.set(x.code,{targetType:'ANGLE',code:x.code,longitude:norm(Number(x.value))});return [...pos.values()];}
function natalHouse1(p){const items=(p.calculation?.structures||[]).find(x=>x.code==='HOUSE_CUSPS')?.items||[];const h1=items.find(x=>x.code==='HOUSE_1');return h1?norm(Number(h1.value)):null;}
function houseNumber(longitude,house1){return house1==null?null:(Math.floor(norm(longitude-house1)/30)%12)+1;}
function signCode(longitude){return SIGNS[Math.floor(norm(longitude)/30)%12];}
export async function executeAstTransitRequest(body,{astronomyModuleLoader}={}){
 assertNatal(body?.natalProjection);const targetContext=normalizeTargetContext(body?.targetContext);if(!body?.requestId)fail('ASTT_REQUEST_ID_REQUIRED',400);if(!body?.consentRecordId)fail('ASTT_CONSENT_RECORD_REQUIRED',400);
 const adapters=createAstronomyEngineProductionAdapters({astronomyModuleLoader});
 const astronomyContext=await adapters.astronomyAdapter.createAstronomyContext({utcIso:targetContext.targetUtcIso,observerMode:'GEOCENTRIC',coordinate:null,requestedTimeScale:'TT',referenceFrame:'ECLIPTIC_OF_DATE',ephemerisVersion:'2.1.19'});
 const planetResult=await adapters.planetEphemerisAdapter.calculateBodies({astronomyContext:{...astronomyContext,utcIso:targetContext.targetUtcIso},bodyCodes:[...ASTA_CORE_BODY_CODES],planetSetCode:'PHI_OS_AST_PLANET_SET_CORE_10_V1',nodePolicyCode:'PHI_OS_AST_NODE_NONE_V1',retrogradePolicyCode:'PHI_OS_AST_LONGITUDE_SPEED_RETROGRADE_V1',precisionPolicyCode:'PHI_OS_AST_DECIMAL_12_V1',engineVersion:'2.1.19'});
 const house1=natalHouse1(body.natalProjection);const transitPositions=planetResult.bodies.map(x=>freeze({bodyCode:x.bodyCode,longitude:norm(x.longitude),signCode:signCode(x.longitude),latitude:Number(x.latitude.toFixed(12)),speedLongitudeDegreesPerDay:Number(x.speedLongitudeDegreesPerDay.toFixed(12)),retrograde:x.retrograde}));
 const houseActivations=transitPositions.map(x=>freeze({bodyCode:x.bodyCode,houseNumber:houseNumber(x.longitude,house1),status:house1==null?'UNAVAILABLE_NATAL_HOUSES':'AVAILABLE'}));
 const targets=natalPoints(body.natalProjection),transitAspects=[];for(const tr of transitPositions)for(const na of targets){const sep=separation(tr.longitude,na.longitude),m=aspectMatch(sep);if(m)transitAspects.push(freeze({transitBodyCode:tr.bodyCode,natalTargetType:na.targetType,natalTargetCode:na.code,aspectCode:m.aspectCode,separationDegrees:sep,orbDegrees:m.orb,authorizedOrbDegrees:m.orbDegrees}));}
 transitAspects.sort((a,b)=>ASTA_CORE_BODY_CODES.indexOf(a.transitBodyCode)-ASTA_CORE_BODY_CODES.indexOf(b.transitBodyCode)||a.natalTargetCode.localeCompare(b.natalTargetCode)||a.aspectCode.localeCompare(b.aspectCode));
 const unknown=[];if(house1==null)unknown.push(freeze({code:'ASTT_NATAL_HOUSES_UNAVAILABLE',scope:'HOUSE_ACTIVATION',rendererMustDisplay:true}));
 const boundaries=freeze({natalRecalculated:false,eventPredictionCreated:false,fortunePredictionCreated:false,professionalJudgmentCreated:false,goodBadScoreCreated:false,methodVotingCreated:false});
 const evidence=freeze([{type:'SOURCE_NATAL_PROJECTION',reference:body.natalProjection.projectionId,status:'AVAILABLE'},{type:'EPHEMERIS_AUTHORITY',reference:'ASTRONOMY_ENGINE_JS@2.1.19',status:'AVAILABLE'},{type:'ASPECT_POLICY',reference:'PHI_OS_AST_ASPECT_ORB_POLICY_V1',status:'AVAILABLE'},{type:'HOUSE_POLICY',reference:'PHI_OS_AST_WHOLE_SIGN_HOUSE_SYSTEM_V1',status:house1==null?'UNAVAILABLE':'AVAILABLE'}]);
 const core={schemaVersion:AST_TRANSIT_PROJECTION_SCHEMA,scopeCode:'AST_TRANSIT_RUNTIME_V2',sourceNatalProjectionId:body.natalProjection.projectionId,targetContext,executionCompleteness:house1==null?'PARTIAL':'COMPLETE',transitPositions:freeze(transitPositions),houseActivations:freeze(houseActivations),transitAspects:freeze(transitAspects),unknown:freeze(unknown),evidence,boundaries,version:freeze({runtimeVersion:AST_TRANSIT_RUNTIME_VERSION,ephemerisVersion:'2.1.19',natalProjectionSchema:body.natalProjection.schemaVersion})};
 const projectionId=`ASTT-${(await sha256(core)).slice(0,24).toUpperCase()}`;return freeze({projection:{projectionId,...core}});
}
