import {sha256} from '../method-runtime/shared-calculation-runtime.js';
import {createAstronomyEngineProductionAdapters} from '../method-client-delivery/production-adapters/astronomy-engine-production-adapter.js';

export const BZR_TEMPORAL_PROJECTION_SCHEMA='PHI-OS-BZR-TEMPORAL-PROJECTION-v1.0.0';
export const BZR_TEMPORAL_RUNTIME_VERSION='2.0.0';
const STEMS=Object.freeze(['JIA','YI','BING','DING','WU','JI','GENG','XIN','REN','GUI']);
const BRANCHES=Object.freeze(['ZI','CHOU','YIN','MAO','CHEN','SI','WU','WEI','SHEN','YOU','XU','HAI']);
const STEM_ELEMENT=Object.freeze({JIA:'WOOD',YI:'WOOD',BING:'FIRE',DING:'FIRE',WU:'EARTH',JI:'EARTH',GENG:'METAL',XIN:'METAL',REN:'WATER',GUI:'WATER'});
const BRANCH_ELEMENT=Object.freeze({ZI:'WATER',CHOU:'EARTH',YIN:'WOOD',MAO:'WOOD',CHEN:'EARTH',SI:'FIRE',WU:'FIRE',WEI:'EARTH',SHEN:'METAL',YOU:'METAL',XU:'EARTH',HAI:'WATER'});
const GENERATES=Object.freeze({WOOD:'FIRE',FIRE:'EARTH',EARTH:'METAL',METAL:'WATER',WATER:'WOOD'});
const CONTROLS=Object.freeze({WOOD:'EARTH',EARTH:'WATER',WATER:'FIRE',FIRE:'METAL',METAL:'WOOD'});
const STEM_COMBINATIONS=new Set([['JIA','JI'],['YI','GENG'],['BING','XIN'],['DING','REN'],['WU','GUI']].map(([a,b])=>pairKey(a,b)));
const BRANCH_COMBINATIONS=new Set([['ZI','CHOU'],['YIN','HAI'],['MAO','XU'],['CHEN','YOU'],['SI','SHEN'],['WU','WEI']].map(([a,b])=>pairKey(a,b)));
const BRANCH_CLASHES=new Set([['ZI','WU'],['CHOU','WEI'],['YIN','SHEN'],['MAO','YOU'],['CHEN','XU'],['SI','HAI']].map(([a,b])=>pairKey(a,b)));
function fail(code,status=422){const e=new Error(code);e.code=code;e.status=status;throw e;}
function freeze(v){if(v&&typeof v==='object'&&!Object.isFrozen(v)){Object.freeze(v);for(const x of Object.values(v))freeze(x)}return v;}
function mod(n,m){return ((n%m)+m)%m;}
function pairKey(a,b){return [a,b].sort().join(':');}
function parseOffset(value){if(!/^[+-](?:0\d|1[0-4]):[0-5]\d$/.test(value||''))fail('BZT_TARGET_UTC_OFFSET_INVALID',400);const sign=value[0]==='-'?-1:1;return sign*(Number(value.slice(1,3))*60+Number(value.slice(4,6)));}
function offsetText(minutes){const sign=minutes<0?'-':'+';const n=Math.abs(minutes);return `${sign}${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;}
function validDate(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))return false;const d=new Date(`${value}T00:00:00Z`);return !Number.isNaN(d.valueOf())&&d.toISOString().slice(0,10)===value;}
function validTime(value){return value==null||/^(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d$/.test(value);}
function localDateForUtc(utcIso,offsetMinutes){return new Date(Date.parse(utcIso)+offsetMinutes*60000).toISOString().slice(0,10);}
function localTimeForUtc(utcIso,offsetMinutes){return new Date(Date.parse(utcIso)+offsetMinutes*60000).toISOString().slice(11,19);}
function localToUtc(date,time,offsetMinutes){const d=new Date(`${date}T${time}${offsetText(offsetMinutes)}`);if(Number.isNaN(d.valueOf()))fail('BZT_TARGET_LOCAL_TIME_INVALID',400);return d.toISOString();}
function daysInMonth(y,m){return new Date(Date.UTC(y,m,0)).getUTCDate();}
function addCivil(dateStr,{years=0,months=0,days=0}={}){const [y0,m0,d0]=dateStr.split('-').map(Number);let total=(y0+years)*12+(m0-1)+months;let y=Math.floor(total/12),m=mod(total,12)+1;let d=Math.min(d0,daysInMonth(y,m));const out=new Date(Date.UTC(y,m-1,d));out.setUTCDate(out.getUTCDate()+days);return out.toISOString().slice(0,10);}
function sexagenaryYear(year){const index=mod(year-4,60)+1;const i=index-1;return Object.freeze({year,stemCode:STEMS[i%10],branchCode:BRANCHES[i%12],sexagenaryIndex:index});}
function normalizeTargetContext(targetContext){const date=targetContext?.targetDate,time=targetContext?.targetTime??null,tz=targetContext?.targetTimezone||{};if(!validDate(date))fail('BZT_TARGET_DATE_REQUIRED',400);if(!validTime(time))fail('BZT_TARGET_TIME_INVALID',400);if(typeof tz.iana!=='string'||!tz.iana.trim())fail('BZT_TARGET_TIMEZONE_REQUIRED',400);const offsetMinutes=parseOffset(tz.utcOffsetAtTarget);return freeze({targetDate:date,targetTime:time,targetTimezone:{iana:tz.iana.trim(),utcOffsetAtTarget:tz.utcOffsetAtTarget,offsetMinutes,source:'EXPLICIT_REQUEST'}});}
function extractNatalPillars(natalProjection){if(natalProjection?.method?.publicMethodCode!=='BAZI_PROJECTION')fail('BZT_REQUIRES_BAZI_NATAL_PROJECTION');const group=(natalProjection.calculation?.structures||[]).find(x=>x.code==='FOUR_PILLARS');if(!group)fail('BZT_NATAL_PILLARS_UNAVAILABLE');const by={};for(const item of group.items||[]){const m=/^(YEAR|MONTH|DAY|HOUR)_(STEM|BRANCH)$/.exec(item.code||'');if(!m)continue;by[m[1]]??={pillarType:m[1],stemCode:null,branchCode:null,sexagenaryIndex:item.meta?.sexagenaryIndex??null};if(m[2]==='STEM')by[m[1]].stemCode=item.value;else by[m[1]].branchCode=item.value;}return Object.freeze(['YEAR','MONTH','DAY','HOUR'].map(k=>by[k]).filter(x=>x?.stemCode&&x?.branchCode).map(freeze));}
function relationElement(left,right){if(!left||!right)return [];if(left===right)return ['SAME'];if(GENERATES[left]===right)return ['GENERATES'];if(GENERATES[right]===left)return ['GENERATED_BY'];if(CONTROLS[left]===right)return ['CONTROLS'];if(CONTROLS[right]===left)return ['CONTROLLED_BY'];return [];}
function stemRelations(a,b){const out=[];if(a===b)out.push('SAME');if(STEM_COMBINATIONS.has(pairKey(a,b)))out.push('COMBINATION');for(const x of relationElement(STEM_ELEMENT[a],STEM_ELEMENT[b]))if(!out.includes(x))out.push(x);return out;}
function branchRelations(a,b){const out=[];if(a===b)out.push('SAME');if(BRANCH_COMBINATIONS.has(pairKey(a,b)))out.push('COMBINATION');if(BRANCH_CLASHES.has(pairKey(a,b)))out.push('CLASH');for(const x of relationElement(BRANCH_ELEMENT[a],BRANCH_ELEMENT[b]))if(!out.includes(x))out.push(x);return out;}
function relationRecord(left,right,scope){return freeze({scope,left:freeze({...left}),right:freeze({...right}),stemRelations:Object.freeze(stemRelations(left.stemCode,right.stemCode)),branchRelations:Object.freeze(branchRelations(left.branchCode,right.branchCode))});}
function deriveCurrentLuck({canonicalInput,targetDate,coreResults}){const luck=coreResults.find(x=>x.algorithmCode==='BZR_LUCK_CYCLE_SEQUENCE');if(!luck?.output)return freeze({status:'UNAVAILABLE',state:'NOT_CALCULATED',current:null,candidates:[],reasonCodes:['BZT_CURRENT_LUCK_REQUIRES_GOVERNED_LUCK_SEQUENCE']});const startAge=luck.output.startAge;if(!startAge||!canonicalInput?.birthDate)return freeze({status:'UNAVAILABLE',state:'NOT_CALCULATED',current:null,candidates:[],reasonCodes:['BZT_CURRENT_LUCK_START_AGE_UNAVAILABLE']});const first=addCivil(canonicalInput.birthDate,{years:startAge.years,months:startAge.months,days:startAge.days});const cycles=(luck.output.cycles||[]).map(c=>freeze({cycleNumber:c.cycleNumber,pillar:freeze({...c.pillar}),startDate:addCivil(first,{years:(c.cycleNumber-1)*10}),endDate:addCivil(first,{years:c.cycleNumber*10}),direction:c.direction}));if(targetDate<first)return freeze({status:'AVAILABLE',state:'PRE_LUCK_CYCLE',current:null,candidates:[],firstCycleStartDate:first,direction:luck.output.direction,startAge:freeze({...startAge}),reasonCodes:[]});for(let i=0;i<cycles.length;i++){const c=cycles[i];if(targetDate===c.startDate){const candidates=[];if(i>0)candidates.push(cycles[i-1]);candidates.push(c);return freeze({status:'PARTIAL',state:'TRANSITION_DAY',current:null,candidates,firstCycleStartDate:first,direction:luck.output.direction,startAge:freeze({...startAge}),reasonCodes:['BZT_LUCK_TRANSITION_DAY_CIVIL_DATE_PRECISION']});}if(targetDate>c.startDate&&targetDate<c.endDate)return freeze({status:'AVAILABLE',state:'ACTIVE',current:c,candidates:[],firstCycleStartDate:first,direction:luck.output.direction,startAge:freeze({...startAge}),reasonCodes:[]});}
const last=cycles.at(-1);if(last&&targetDate===last.endDate)return freeze({status:'PARTIAL',state:'TRANSITION_DAY_OUTSIDE_GENERATED_RANGE',current:null,candidates:[last],firstCycleStartDate:first,direction:luck.output.direction,startAge:freeze({...startAge}),reasonCodes:['BZT_TARGET_ON_END_OF_GENERATED_LUCK_RANGE']});return freeze({status:'PARTIAL',state:'OUTSIDE_GENERATED_RANGE',current:null,candidates:[],firstCycleStartDate:first,direction:luck.output.direction,startAge:freeze({...startAge}),reasonCodes:['BZT_TARGET_OUTSIDE_GENERATED_LUCK_CYCLE_RANGE']});}
async function deriveAnnual({targetContext,astronomyModuleLoader}){const target=normalizeTargetContext(targetContext),offset=target.targetTimezone.offsetMinutes,year=Number(target.targetDate.slice(0,4));const adapters=createAstronomyEngineProductionAdapters({astronomyModuleLoader});const solar=await adapters.solarTermAdapter.resolveYearContext({gregorianYear:year});const li=solar.liChunUtcIso,liLocalDate=localDateForUtc(li,offset),liLocalTime=localTimeForUtc(li,offset);if(target.targetDate===liLocalDate&&target.targetTime==null)return freeze({status:'PARTIAL',annualPillar:null,liChunUtcIso:li,liChunLocalDate:liLocalDate,liChunLocalTime:liLocalTime,targetContext:target,reasonCodes:['BZT_ANNUAL_BOUNDARY_TIME_REQUIRED']});let after;if(target.targetDate<liLocalDate)after=false;else if(target.targetDate>liLocalDate)after=true;else after=Date.parse(localToUtc(target.targetDate,target.targetTime,offset))>=Date.parse(li);const annualYear=after?year:year-1;return freeze({status:'AVAILABLE',annualPillar:sexagenaryYear(annualYear),liChunUtcIso:li,liChunLocalDate:liLocalDate,liChunLocalTime:liLocalTime,targetContext:target,reasonCodes:[]});}
export async function buildBzrTemporalProjection({requestId,canonicalInput,targetContext,natalProjection,baseExecution},{astronomyModuleLoader}={}){
 const target=normalizeTargetContext(targetContext);const natalPillars=extractNatalPillars(natalProjection);const coreResults=baseExecution?.partialExecution?.coreResults||[];const annual=await deriveAnnual({targetContext:target,astronomyModuleLoader});const luck=deriveCurrentLuck({canonicalInput,targetDate:target.targetDate,coreResults});const relations=[];const annualPillar=annual.annualPillar;const luckPillar=luck.current?.pillar||null;
 if(annualPillar){for(const p of natalPillars)relations.push(relationRecord({...annualPillar,pillarType:'ANNUAL'},{...p},`ANNUAL_TO_NATAL_${p.pillarType}`));}
 if(luckPillar){for(const p of natalPillars)relations.push(relationRecord({...luckPillar,pillarType:'LUCK'},{...p},`LUCK_TO_NATAL_${p.pillarType}`));if(annualPillar)relations.push(relationRecord({...annualPillar,pillarType:'ANNUAL'},{...luckPillar,pillarType:'LUCK'},'ANNUAL_TO_CURRENT_LUCK'));}
 const reasonCodes=[...(annual.reasonCodes||[]),...(luck.reasonCodes||[])];const completeness=annual.status==='AVAILABLE'&&(luck.status==='AVAILABLE')?'COMPLETE':'PARTIAL';const base={schemaVersion:BZR_TEMPORAL_PROJECTION_SCHEMA,capabilityCode:'BZR_TEMPORAL',capabilityVersion:BZR_TEMPORAL_RUNTIME_VERSION,sourceMethodCode:'BAZI',sourcePluginCode:'BZR',sourceNatalProjectionId:natalProjection.projectionId,targetContext:target,executionCompleteness:completeness,natal:freeze({pillars:natalPillars}),currentLuckCycle:luck,annualContext:annual,relations:Object.freeze(relations),unknown:Object.freeze(reasonCodes.map(code=>freeze({code,rendererMustDisplay:true}))),evidence:Object.freeze([{type:'NATAL_PROJECTION',reference:natalProjection.projectionId,version:natalProjection.schemaVersion},{type:'LUCK_CYCLE_AUTHORITY',reference:'PHI-OS-BZRA-W4-LUCK-CYCLE-POLICY-FREEZE-v1.0.0',version:'1.0.0'},{type:'ANNUAL_BOUNDARY_AUTHORITY',reference:'EXACT_LI_CHUN_INSTANT',version:'1.0.0'},{type:'SOLAR_TERM_ENGINE',reference:'ASTRONOMY_ENGINE_JS',version:'2.1.19'}].map(freeze)),boundaries:freeze({natalRecalculated:false,tenGodsCreated:false,usefulGodCreated:false,patternClassificationCreated:false,fortunePredictionCreated:false,eventPredictionCreated:false,professionalJudgmentCreated:false,goodBadScoreCreated:false,methodVotingCreated:false})};const projectionId=`BZTP-${(await sha256({natalProjectionId:base.sourceNatalProjectionId,targetContext:base.targetContext,currentLuckCycle:base.currentLuckCycle,annualContext:base.annualContext,relations:base.relations,version:base.capabilityVersion})).slice(0,24).toUpperCase()}`;return freeze({...base,projectionId,execution:freeze({requestId,executedAt:new Date().toISOString(),productionAcceptedScope:true})});
}
