import { spawnSync } from 'node:child_process';
export const ACTIVE_PJA_TOPOLOGY = [
  ['w0','scripts/check-pja-w0-cross-system-boundary.mjs'],['w1','scripts/check-pja-w1-blueprint-led-knowledge.mjs'],['w2a','scripts/check-pja-w2a-canonical-article-editorial-contract.mjs'],['w2b','scripts/check-pja-w2b-structured-article-schema.mjs'],['w2c','scripts/check-pja-w2c-claim-source-review-governance.mjs'],['w2d','scripts/check-pja-w2d-article-renderer-expansion.mjs'],['w2e','scripts/check-pja-w2e-production-tools.mjs'],['w2e-r1','scripts/check-pja-w2e-r1-production-brief-hardening.mjs'],['w2f-a','scripts/check-pja-w2f-a-universal-production-readiness.mjs'],['w2f-b1','scripts/check-pja-w2f-b1-preface-content-population.mjs'],['w2f-b2','scripts/check-pja-w2f-b2-preface-article-production.mjs'],['w2f-b2a','scripts/check-pja-w2f-b2a-first-human-frozen-pilot.mjs'],['w2f-b2b','scripts/check-pja-w2f-b2b-schema-validator-alignment.mjs'],['c0','scripts/check-pja-w2f-c0-book-i-registry-population.mjs'],['c1','scripts/check-pja-w2f-c1-readiness-skeleton-population.mjs'],['c2','scripts/check-pja-w2f-c2-canonical-thesis-boundary-freeze.mjs'],['c3','scripts/check-pja-w2f-c3-universal-production-readiness.mjs'],['d','scripts/check-pja-w2f-d-book-i-batch-production.mjs'],['c3r1','scripts/check-pja-w2f-c3r1-preface-production-readiness-closure.mjs'],['w3a','scripts/check-pja-w3a-editorial-package-foundation.mjs'],['w3r','scripts/check-pja-w3r-production-workflow-review.mjs'],['w3r1','scripts/check-pja-w3r1-scalable-article-production.mjs']
];
const args=process.argv.slice(2), nodeIndex=args.indexOf('--node');
if(nodeIndex>=0){const result=spawnSync(process.execPath,['scripts/check-pja-node.mjs',args[nodeIndex+1]],{encoding:'utf8'});process.stdout.write(result.stdout);process.stderr.write(result.stderr);process.exit(result.status??1);}
const from=option('--from')||ACTIVE_PJA_TOPOLOGY[0][0],to=option('--to')||ACTIVE_PJA_TOPOLOGY.at(-1)[0],start=ACTIVE_PJA_TOPOLOGY.findIndex(([id])=>id===from),end=ACTIVE_PJA_TOPOLOGY.findIndex(([id])=>id===to);
if(start<0||end<start){console.error('INVALID_CHECK_RANGE');process.exit(2);} const selected=ACTIVE_PJA_TOPOLOGY.slice(start,end+1),executed=new Set(),began=performance.now();
for(const [id,script] of selected){if(executed.has(script)){console.error(`DUPLICATE_CHECKER:${script}`);process.exit(2);}executed.add(script);const at=performance.now(),result=spawnSync(process.execPath,[script],{encoding:'utf8'});if(result.status!==0){process.stderr.write(result.stdout);process.stderr.write(result.stderr);console.error(`PJA_CHECK_FAILED:${id}`);process.exit(result.status??1);}console.log(`✓ ${id} (${Math.round(performance.now()-at)} ms)`);}
console.log(JSON.stringify({status:'passed',from,to,checkerCount:selected.length,uniqueCheckerCount:executed.size,duplicateExecutions:0,elapsedMs:Math.round(performance.now()-began)},null,2));
function option(name){const index=args.indexOf(name);return index>=0?args[index+1]:null;}
